/* Generated by Together */
package com.izhuantou.damain.vo;

import java.math.BigDecimal;
import java.util.Date;

import com.izhuantou.damain.BasePojo;

/**
 * 收益返回计划（出借人）
 * 
 * @author zhangchi
 * @version 1.0
 */
public class CustomerTyjDTO extends BasePojo {

    // 体验金

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    /**
     * 登录人ID
     */
    private String memberOID;
    /**
     * 登录人手机
     */
    private String mobile;
    /**
     * 体验用户
     */
    private String nameCN;

    /**
     * 体验金金额
     */
    private BigDecimal tyjPrice;

    /**
     * 是否已使用(0获得未到期,1已可以使用,2使用过)
     */
    private String isUsed;

    private Integer tyjNum;
    private Integer experienceMember;
    private Date addDateTime;

    private Date endDateTime;

    private String TYJSY;
    private String TyjFlag;

    public String getTyjFlag() {
	return TyjFlag;
    }

    public void setTyjFlag(String tyjFlag) {
	TyjFlag = tyjFlag;
    }

    public String getTYJSY() {
	return TYJSY;
    }

    public void setTYJSY(String tYJSY) {
	TYJSY = tYJSY;
    }

    public Date getEndDateTime() {
	return endDateTime;
    }

    public void setEndDateTime(Date endDateTime) {
	this.endDateTime = endDateTime;
    }

    public static long getSerialversionuid() {
	return serialVersionUID;
    }

    public Integer getExperienceMember() {
	return experienceMember;
    }

    public void setExperienceMember(Integer experienceMember) {
	this.experienceMember = experienceMember;
    }

    public Integer getTyjNum() {
	return tyjNum;
    }

    public void setTyjNum(Integer tyjNum) {
	this.tyjNum = tyjNum;
    }

    /**
     * 结算对应资金池OID
     */
    private String cashPoolOID;

    public Date getAddDateTime() {
	return addDateTime;
    }

    public void setAddDateTime(Date addDateTime) {
	this.addDateTime = addDateTime;
    }

    public String getMemberOID() {
	return memberOID;
    }

    public void setMemberOID(String memberOID) {
	this.memberOID = memberOID;
    }

    public BigDecimal getTyjPrice() {
	return tyjPrice;
    }

    public void setTyjPrice(BigDecimal tyjPrice) {
	this.tyjPrice = tyjPrice;
    }

    public String getIsUsed() {
	return isUsed;
    }

    public void setIsUsed(String isUsed) {
	this.isUsed = isUsed;
    }

    public String getMobile() {
	return mobile;
    }

    public void setMobile(String mobile) {
	this.mobile = mobile;
    }

    public String getNameCN() {
	return nameCN;
    }

    public void setNameCN(String nameCN) {
	this.nameCN = nameCN;
    }

    public String getCashPoolOID() {
	return cashPoolOID;
    }

    public void setCashPoolOID(String cashPoolOID) {
	this.cashPoolOID = cashPoolOID;
    }

    @Override
    public String toString() {
	return "PAY_CustomerTyj [memberOID=" + memberOID + ", mobile=" + mobile + ", nameCN=" + nameCN + ", tyjPrice="
		+ tyjPrice + ", isUsed=" + isUsed + ", tyjNum=" + tyjNum + ", experienceMember=" + experienceMember
		+ ", addDateTime=" + addDateTime + ", endDateTime=" + endDateTime + ", TYJSY=" + TYJSY + ", TyjFlag="
		+ TyjFlag + ", cashPoolOID=" + cashPoolOID + "]";
    }

}
